require_relative '../node_modules/react-native/scripts/react_native_pods'

platform :ios, '15.1'
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'RechargeRest' do
  use_react_native!(
    path: '../node_modules/react-native',
    app_path: '..'
  )

  use_native_modules!

  post_install do |installer|
    react_native_post_install(
      installer,
      '../node_modules/react-native',
      mac_catalyst_enabled: false
    )
  end
end
